
var map_config = {
    'default': {
        'borderColor': '#666666', //inter-state borders
        'lakesColor': '#ffffff', // lakes color
        'namesColor': '#919191', //color of short names
        'mapShadow': '#000', //shadow color below the map
        'shadowOpacity': '0', //shadow opacity, value, 0-100
        'hoverShadow': '#666666', //tooltip shadow color
    },
    'map_1': {
        'hover': 'ALABAMA', //state hover content
        'url': 'http://www.html5interactivemaps.com/', //Goto URL
        'target': 'None', //open link in new window:new_window, open in current window:same_window, or none for nothing.
        'upColor': '#767c83', //state's color when page loads
        'overColor': '#FFEE88', //state's color when mouse hover
        'downColor': '#FFEE88', //state's color when mouse clicking
        'enable': false, //true/false to enable/disable this state
    },
    'map_2': {
        'hover': 'ALASKA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#ffffff',
        'overColor': '#ffffff',
        'downColor': '#ffffff',
        'enable': false,
    },
    'map_3': {
        'hover': 'ARIZONA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_4': {
        'hover': 'ARKANSAS',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_5': {
        'hover': 'CALIFORNIA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_6': {
        'hover': 'COLORADO',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_7': {
        'hover': 'CONNECTICUT',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_8': {
        'hover': 'DELAWARE',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_9': {
        'hover': 'FLORIDA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_10': {
        'hover': 'GEORGIA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_11': {
        'hover': 'HAWAII',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#ffffff',
        'overColor': '#ffffff',
        'downColor': '#ffffff',
        'enable': false,
    },
    'map_12': {
        'hover': 'IDAHO',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_13': {
        'hover': 'ILLINOIS',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_14': {
        'hover': 'INDIANA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_15': {
        'hover': 'IOWA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_16': {
        'hover': 'KANSAS',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_17': {
        'hover': 'KENTUCKY',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_18': {
        'hover': 'LOUISIANA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_19': {
        'hover': 'MAINE',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_20': {
        'hover': 'MARYLAND',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_21': {
        'hover': 'MASSACHUSETTS',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_22': {
        'hover': 'MICHIGAN',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_23': {
        'hover': 'MINNESOTA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_24': {
        'hover': 'MISSISSIPPI',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_25': {
        'hover': 'MISSOURI',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_26': {
        'hover': 'MONTANA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_27': {
        'hover': 'NEBRASKA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_28': {
        'hover': 'NEVADA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_29': {
        'hover': 'NEW HAMPSHIRE',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_30': {
        'hover': 'NEW JERSEY',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_31': {
        'hover': 'NEW MEXICO',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_32': {
        'hover': 'NEW YORK',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_33': {
        'hover': 'NORTH CAROLINA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_34': {
        'hover': 'NORTH DAKOTA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_35': {
        'hover': 'OHIO',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_36': {
        'hover': 'OKLAHOMA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_37': {
        'hover': 'OREGON',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_38': {
        'hover': 'PENNSYLVANIA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_39': {
        'hover': 'RHODE ISLAND',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_40': {
        'hover': 'SOUTH CAROLINA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#FFEE88',
        'enable': false,
    },
    'map_41': {
        'hover': 'SOUTH DAKOTA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#FFEE88',
        'enable': false,
    },
    'map_42': {
        'hover': 'TENNESSEE',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_43': {
        'hover': '<b><u>TEXAS</u></b><br><img src="example.png">Here you can write some <b>HTML</b><br>formated text.<br>This state when clicked will<br>open the URL in the <span style="color:black; background-color:#a9f038;"><b>SAME</b></span><br>window.',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_44': {
        'hover': 'UTAH',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_45': {
        'hover': 'VERMONT',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_46': {
        'hover': 'VIRGINIA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_47': {
        'hover': 'WASHINGTON',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_48': {
        'hover': 'WEST VIRGINIA',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_49': {
        'hover': 'WISCONSIN',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
    'map_50': {
        'hover': 'WYOMING',
        'url': 'http://www.html5interactivemaps.com/',
        'target': 'None',
        'upColor': '#767c83',
        'overColor': '#FFEE88',
        'downColor': '#993366',
        'enable': false,
    },
} 