
var pin_config = {
    'default': {
        'pinShadow': '#000', //shadow color below the points
        'pinShadowOpacity': '0', //shadow opacity, value, 0-100
    },
    'points': [

    {
        'shape': 'circle',
        'hover': 'LIBERTY PARK, CAMDEN<br><span style="font-size: 12px"><strong style="color: red">1 IN 11</strong> WILL BE A VICTIM IN 2016</span>',
        'pos_X': 700,
        'pos_Y': 168,
        'diameter': 17,
        'outlINe': '#FFF',
        'thickness': 0,
        'upColor': '#FFFFFF',
        'overColor': '#FF0000',
        'downColor': '#ff0000',
        'url': 'http://www.html5INteractivemaps.com',
        'target': 'None',
        'enable': true,
    },

    {
        'shape': 'circle',
        'hover': 'SUNNYSIDE, HOUSTON<br><span style="font-size: 12px"><strong style="color: red">1 IN 11</strong> WILL BE A VICTIM IN 2016</span>',
        'pos_X': 420,
        'pos_Y': 408,
        'diameter': 17,
        'outlINe': '#FFF',
        'thickness': 0,
        'upColor': '#FFFFFF',
        'overColor': '#FF0000',
        'downColor': '#FF0000',
        'url': 'http://www.html5INteractivemaps.com',
        'target': 'none',
        'enable': true,
    }, {
        'shape': 'circle',
        'hover': 'WEST ENGLEWOOD, CHICAGO<br><span style="font-size: 12px"><strong style="color: red">1 IN 17</strong> WILL BE A VICTIM IN 2016</span>',
        'pos_X': 513,
        'pos_Y': 184,
        'diameter': 17,
        'outlINe': '#FFF',
        'thickness': 0,
        'upColor': '#FFFFFF',
        'overColor': '#FF0000',
        'downColor': '#ff0000',
        'url': 'http://www.html5INteractivemaps.com',
        'target': 'None',
        'enable': true,
    }, {
        'shape': 'circle',
        'hover': 'SOUTH MEMPHIS<br><span style="font-size: 12px"><strong style="color: red">1 IN 11</strong> WILL BE A VICTIM IN 2016</span>',
        'pos_X': 499,
        'pos_Y': 299,
        'diameter': 17,
        'outlINe': '#FFF',
        'thickness': 0,
        'upColor': '#FFFFFF',
        'overColor': '#FF0000',
        'downColor': '#ff0000',
        'url': 'http://www.html5INteractivemaps.com',
        'target': 'None',
        'enable': true,
    }, {
        'shape': 'circle',
        'hover': 'WEST OAKLAND<br><span style="font-size: 12px"><strong style="color: red">1 IN 14</strong> WILL BE A VICTIM IN 2016</span>',
        'pos_X': 43,
        'pos_Y': 213,
        'diameter': 17,
        'outlINe': '#FFF',
        'thickness': 0,
        'upColor': '#FFFFFF',
        'overColor': '#FF0000',
        'downColor': '#ff0000',
        'url': 'http://www.html5INteractivemaps.com',
        'target': 'None',
        'enable': true,
    }, {
        'shape': 'circle',
        'hover': 'NORTHVIEW HEIGHTS, PITTSBURGH<br><span style="font-size: 12px"><strong style="color: red">1 IN 13</strong> WILL BE A VICTIM IN 2016  </span>',
        'pos_X': 622,
        'pos_Y': 174,
        'diameter': 17,
        'outlINe': '#FFF',
        'thickness': 0,
        'upColor': '#FFFFFF',
        'overColor': '#FF0000',
        'downColor': '#ff0000',
        'url': 'http://www.html5INteractivemaps.com',
        'target': 'None',
        'enable': true,
    }, {
        'shape': 'circle',
        'hover': 'EAST ST. LOUIS<br><span style="font-size: 12px"><strong style="color: red">1 IN 13</strong> WILL BE A VICTIM IN 2016  </span>',
        'pos_X': 487,
        'pos_Y': 237,
        'diameter': 17,
        'outlINe': '#FFF',
        'thickness': 0,
        'upColor': '#FFFFFF',
        'overColor': '#FF0000',
        'downColor': '#ff0000',
        'url': 'http://www.html5INteractivemaps.com',
        'target': 'None',
        'enable': true,
    }, {
        'shape': 'circle',
        'hover': 'N FREMONT AVENUE, BALTIMORE<br><span style="font-size: 12px"><strong style="color: red">1 IN 11</strong> WILL BE A VICTIM IN 2016  </span>',
        'pos_X': 672,
        'pos_Y': 197,
        'diameter': 17,
        'outlINe': '#FFF',
        'thickness': 0,
        'upColor': '#FFFFFF',
        'overColor': '#FF0000',
        'downColor': '#ff0000',
        'url': 'http://www.html5INteractivemaps.com',
        'target': 'None',
        'enable': true,
    }, {
        'shape': 'circle',
        'hover': 'CORE CITY, DETROIT<br><span style="font-size: 12px"><strong style="color: red">1 IN 13</strong> WILL BE A VICTIM IN 2016  </span>',
        'pos_X': 570,
        'pos_Y': 163,
        'diameter': 17,
        'outlINe': '#FFF',
        'thickness': 0,
        'upColor': '#FFFFFF',
        'overColor': '#FF0000',
        'downColor': '#ff0000',
        'url': 'http://www.html5INteractivemaps.com',
        'target': 'None',
        'enable': true,
    },


    {
        'shape': 'circle',
        'hover': 'VERMONT VISTA, LOS ANGELES<br><span style="font-size: 12px"><strong style="color: red">1 IN 25</strong> WILL BE A VICTIM IN 2016</span>',
        'pos_X': 86,
        'pos_Y': 291,
        'diameter': 17,
        'outlINe': '#FFF',
        'thickness': 0,
        'upColor': '#FFFFFF',
        'overColor': '#FF0000',
        'downColor': '#Ff0000',
        'url': 'http://www.sharethesafety.org',
        'target': 'None',
        'enable': true,
    },




    ]
} 